

### CommentController::createComment
POST http://localhost:8080/api/v1/comments
Content-Type: application/json

{
  "postTitle":"Samsung",
   "postBody":"postBody",
   "bookId":"2"
}


### CommentController::getCommentList
GET http://localhost:8080/api/v1/comments
Content-Type: application/json

### CommentController::getCommentById
GET http://localhost:8080/api/v1/comments/2
Content-Type: application/json