### PostController::createPost
POST http://localhost:8080/api/v1/posts
Content-Type: application/json

{
  "postTitle":"Samsung",
   "postBody":"postBody",
   "bookId":"2"
}


### PostController::getPostList
GET http://localhost:8080/api/v1/posts
Content-Type: application/json


### PostController::createPost
GET http://localhost:8080/api/v1/posts/1
Content-Type: application/json



### PostController::createPost
UPDATE http://localhost:8080/api/v1/posts/1
Content-Type: application/json


### PostController::createPost
DELETE http://localhost:8080/api/v1/posts/1
Content-Type: application/json
